# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Case3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Case3
  pod 'Charts'

  target 'Case3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Case3UITests' do
    # Pods for testing
  end

end
