# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Case4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Case4
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'

  target 'Case4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Case4UITests' do
    # Pods for testing
  end

end
